### ISSUE TITLE
these links are dead

### ISSUE THREAD

**Issue by jharenza** [d3b-center/bix-onboard-material#4]
To use ssh tunnel to the dev bastion, add your public key to here and the a pull request: https://github.com/kids-first/aws-bastion-host-access/blob/master/vars/main.yml
Upgrade your ~/.ssh/config file by adding Host from here https://github.com/kids-first/aws-infra-toolbox/blob/master/configs/ssh_config

**Comment by yuankunzhu** [comment]
updated the links by this push: https://github.com/d3b-center/bix-onboard-material/commit/967ff9dcf25ca5c390321d2d8edb6df814128f6e
